from stochastic_simulation import SimulationParams, run_replications, simulate_one


def main() -> None:
    # These parameters demonstrate one SNAP call-center simulation run.
    # Time is measured in model days; rates are measured per model day.
    params = SimulationParams(
        # Total simulation horizon: run for 100 model days.
        T=100.0,
        # First 20 model days are warmup and excluded from final statistics.
        warmup=20.0,
        # Number of agents who can serve callers simultaneously.
        c=52,
        # Exogenous fresh-arrival rate.
        lam=623.3,
        # Successful service completion rate for each caller in service.
        mu_plus=13.5,
        # Failed service completion rate for each caller in service.
        mu_minus=13.5,
        # Abandon-and-lost rate for each waiting caller.
        thetaA=4.0,
        # Abandonment rate into the short-redial pool.
        thetaS=3.0,
        # Abandonment rate into the long-redial pool.
        thetaL=3.0,
        # Recertification-call rate generated by pool B.
        deltaB=1 / 130,
        # Return-call rate from the short-redial pool.
        deltaS=3.0,
        # Return-call rate from the long-redial pool.
        deltaL=1 / 9,
        # Natural departure rate from pool B.
        gamma=1 / 260,
        # Initial number of callers in the system.
        q0=0,
        # Initial size of pool B.
        b0=0,
        # Initial size of the short-redial pool.
        rs0=0,
        # Initial size of the long-redial pool.
        rl0=0,
        # Random seed for reproducible demo output.
        seed=123,
    )

    # Run one replication and print the full SimulationResult.
    result = simulate_one(params)
    print(result)

    # Run five independent replications and print selected commonly used metrics.
    frame = run_replications(params, 5)
    print(
        frame[
            [
                "replication",
                "seed",
                "total_arrival_rate_per_model_day",
                "average_wait_including_abandonments_minutes",
                "average_speed_to_answer_minutes",
                "abandonment_fraction",
                "procedural_denial_rate_per_model_day",
            ]
        ].to_string(index=False)
    )


if __name__ == "__main__":
    main()
