"""Event-driven stochastic simulator for the SNAP call center model.

This module implements a continuous-time, event-driven stochastic simulator.
At each simulation step, it samples the time of the next event from the total
event rate, then samples the event type in proportion to each event's rate.

The model's base time unit is one model day. Wait-time outputs are converted
to minutes with ``MINUTES_PER_MODEL_DAY``.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, replace
import math
from typing import Optional

import numpy as np
import pandas as pd


# Number of minutes represented by one model day; 540 minutes is a 9-hour day.
MINUTES_PER_MODEL_DAY = 540.0

EVENT_NAMES = (
    "fresh_arrival",
    "recertification_arrival",
    "short_redial_arrival",
    "long_redial_arrival",
    "abandon_lost",
    "abandon_short",
    "abandon_long",
    "service_success",
    "service_failure",
    "enrolled_departure",
)


@dataclass(frozen=True)
class SimulationParams:
    """Inputs for one continuous-time simulation replication.

    These parameters define the exogenous conditions for one independent
    replication. All rate parameters are expressed per model day; for example,
    ``lam=20`` means an average of 20 fresh arrivals per model day. Queue and
    population parameters are measured as counts of callers or individuals.
    """

    # Total simulation horizon. The event loop runs until simulation time reaches T.
    T: float
    # Warmup period. Events before warmup affect state evolution but not statistics.
    warmup: float
    # Number of servers/agents and the maximum number of concurrent services.
    c: int

    # Exogenous arrival rate of new callers.
    lam: float
    # Successful service completion rate for each caller in service; success enters B.
    mu_plus: float
    # Failed service completion rate for each caller in service; failure enters RL.
    mu_minus: float
    # Abandonment-and-loss rate for each waiting caller.
    thetaA: float
    # Abandonment rate into the short-redial pool RS for each waiting caller.
    thetaS: float
    # Abandonment rate into the long-redial pool RL for each waiting caller.
    thetaL: float
    # Recertification-call rate generated by each individual in pool B.
    deltaB: float
    # Return-call rate for each individual in the short-redial pool RS.
    deltaS: float
    # Return-call rate for each individual in the long-redial pool RL.
    deltaL: float
    # Natural departure rate for each individual in pool B.
    gamma: float

    # Initial number of callers in the system; up to min(q0, c) start in service.
    q0: int = 0
    # Initial size of pool B.
    b0: int = 0
    # Initial size of the short-redial pool RS.
    rs0: int = 0
    # Initial size of the long-redial pool RL.
    rl0: int = 0
    # Random seed. The same seed produces a reproducible single replication.
    seed: Optional[int] = None


@dataclass(frozen=True)
class SimulationResult:
    """Summary statistics and invariant diagnostics for one replication.

    Count fields include only events after warmup. State fields, such as
    final_Q and min_B, describe states observed at the end of or during the
    full simulation path.
    """

    # Total arrivals after warmup, including fresh, recertification, and redial calls.
    total_arrivals: int
    # Number of exogenous fresh arrivals.
    fresh_arrivals: int
    # Number of recertification arrivals generated by pool B.
    recertification_arrivals: int
    # Number of return calls from the short-redial pool RS.
    short_redial_arrivals: int
    # Number of return calls from the long-redial pool RL.
    long_redial_arrivals: int
    # Number of successful service completions; successful callers enter B.
    service_successes: int
    # Number of failed service completions; failed callers enter RL.
    service_failures: int
    # Number of waiting callers who abandon and leave the system.
    abandon_lost: int
    # Number of waiting callers who abandon into the short-redial pool RS.
    abandon_short: int
    # Number of waiting callers who abandon into the long-redial pool RL.
    abandon_long: int
    # Total number of abandonment events across all abandonment routes.
    total_abandonments: int

    # Time-average total system occupancy Q: waiting callers plus callers in service.
    mean_Q: float
    # Time-average waiting queue length.
    mean_waiting: float
    # Time-average size of pool B.
    mean_B: float
    # Time-average size of the short-redial pool RS.
    mean_RS: float
    # Time-average size of the long-redial pool RL.
    mean_RL: float
    # Server utilization: busy server time divided by c * observation_time.
    utilization: float

    # Mean wait for all callers who leave waiting, including answered and abandoned.
    average_wait_including_abandonments_minutes: float
    # Average speed to answer among callers who reach service, in minutes.
    average_speed_to_answer_minutes: float
    # Mean time to abandonment among callers who abandon, in minutes.
    average_time_to_abandonment_minutes: float
    # Abandonment fraction: total_abandonments / total_arrivals.
    abandonment_fraction: float
    # Procedural denial rate, represented here by abandon-and-lost events per model day.
    procedural_denial_rate_per_model_day: float
    # Total arrival rate after warmup, measured per model day.
    total_arrival_rate_per_model_day: float
    # Effective arrival rate: non-abandoned arrivals divided by observation time.
    effective_arrival_rate_per_model_day: float
    # Returning-call rate from recertification, short-redial, and long-redial arrivals.
    returning_call_rate_per_model_day: float

    # Total number of callers in the system at the end of the simulation.
    final_Q: int
    # Waiting queue length at the end of the simulation.
    final_waiting: int
    # Number of callers in service at the end of the simulation.
    final_in_service: int
    # Size of pool B at the end of the simulation.
    final_B: int
    # Size of the short-redial pool RS at the end of the simulation.
    final_RS: int
    # Size of the long-redial pool RL at the end of the simulation.
    final_RL: int
    # Minimum Q observed during the simulation, used as a diagnostic.
    min_Q: int
    # Minimum B observed during the simulation.
    min_B: int
    # Minimum RS observed during the simulation.
    min_RS: int
    # Minimum RL observed during the simulation.
    min_RL: int
    # Maximum number of callers simultaneously in service; should not exceed c.
    max_in_service: int
    # Aggregate proxy: abandonments divided by fresh arrivals.
    abandonments_per_fresh_arrival: float
    # Aggregate proxy: abandonments divided by fresh plus recertification arrivals.
    abandonments_per_external_arrival: float
    # Aggregate proxy: redial arrivals divided by fresh arrivals.
    redial_arrivals_per_fresh_arrival: float
    # Aggregate proxy: redial arrivals divided by fresh plus recertification arrivals.
    redial_arrivals_per_external_arrival: float
    # Aggregate proxy: all attempts divided by fresh arrivals.
    total_attempts_per_fresh_arrival: float
    # Aggregate proxy: all attempts divided by fresh plus recertification arrivals.
    total_attempts_per_external_arrival: float
    # Aggregate proxy: redial arrivals divided by all arrivals.
    repeat_attempt_share: float

    def to_dict(self) -> dict[str, int | float]:
        """Return the result as a flat dictionary suitable for a DataFrame row."""

        return asdict(self)


def _validate_params(params: SimulationParams) -> None:
    """Validate model parameters before running stochastic dynamics.

    Validation covers three groups:
    1. continuous-time and rate parameters must be finite real values;
    2. the time range must be valid, with warmup shorter than T;
    3. population, capacity, and seed fields must be nonnegative integers.
    """

    # These fields may be int or float, but not inf, -inf, or nan.
    real_fields = (
        "T",
        "warmup",
        "lam",
        "mu_plus",
        "mu_minus",
        "thetaA",
        "thetaS",
        "thetaL",
        "deltaB",
        "deltaS",
        "deltaL",
        "gamma",
    )
    for name in real_fields:
        value = getattr(params, name)
        if not math.isfinite(value):
            raise ValueError(f"{name} must be finite")

    # T is the simulation endpoint and must be positive; warmup is discarded time.
    if params.T <= 0:
        raise ValueError("T must be positive")
    if params.warmup < 0 or params.warmup >= params.T:
        raise ValueError("warmup must satisfy 0 <= warmup < T")

    # Apart from T and warmup, the real-valued fields are event rates.
    for name in real_fields[2:]:
        if getattr(params, name) < 0:
            raise ValueError(f"{name} must be nonnegative")

    # c, q0, b0, rs0, and rl0 are capacities or population counts.
    integer_fields = ("c", "q0", "b0", "rs0", "rl0")
    for name in integer_fields:
        value = getattr(params, name)
        if not isinstance(value, (int, np.integer)) or isinstance(value, bool):
            raise ValueError(f"{name} must be an integer")
        if value < 0:
            raise ValueError(f"{name} must be nonnegative")

    # seed may be None; otherwise it must be a nonnegative integer, excluding bool.
    if params.seed is not None:
        if not isinstance(params.seed, (int, np.integer)) or isinstance(params.seed, bool):
            raise ValueError("seed must be an integer or None")
        if params.seed < 0:
            raise ValueError("seed must be nonnegative")


def _safe_divide(numerator: float, denominator: float) -> float:
    """Return numerator / denominator, using 0.0 when the denominator is zero."""

    return float(numerator / denominator) if denominator != 0 else 0.0


def sample_event(rates: np.ndarray, total_rate: float, rng: np.random.Generator) -> int:
    """Sample one event index from nonnegative rates.

    The draw is in [0, total_rate), so ``searchsorted(..., side="right")`` returns
    an index in the valid range whenever rates are nonnegative and total_rate > 0.
    """

    draw = rng.random() * total_rate
    return int(np.searchsorted(np.cumsum(rates), draw, side="right"))


def compute_repeat_attempt_proxies(result_or_mapping) -> dict[str, float]:
    """Compute aggregate proxy metrics for repeated system attempts.

    These are flow-ratio approximations based on aggregate counts. They do not
    reconstruct caller-level histories or exact per-caller attempt counts.
    """

    def get_value(name: str) -> float:
        if isinstance(result_or_mapping, dict):
            return float(result_or_mapping.get(name, 0.0))
        return float(getattr(result_or_mapping, name, 0.0))

    fresh_arrivals = get_value("fresh_arrivals")
    recertification_arrivals = get_value("recertification_arrivals")
    short_redial_arrivals = get_value("short_redial_arrivals")
    long_redial_arrivals = get_value("long_redial_arrivals")
    total_abandonments = get_value("total_abandonments")
    total_arrivals = get_value("total_arrivals")

    redial_arrivals = short_redial_arrivals + long_redial_arrivals
    external_arrivals = fresh_arrivals + recertification_arrivals

    return {
        "abandonments_per_fresh_arrival": _safe_divide(
            total_abandonments, fresh_arrivals
        ),
        "abandonments_per_external_arrival": _safe_divide(
            total_abandonments, external_arrivals
        ),
        "redial_arrivals_per_fresh_arrival": _safe_divide(
            redial_arrivals, fresh_arrivals
        ),
        "redial_arrivals_per_external_arrival": _safe_divide(
            redial_arrivals, external_arrivals
        ),
        "total_attempts_per_fresh_arrival": _safe_divide(
            total_arrivals, fresh_arrivals
        ),
        "total_attempts_per_external_arrival": _safe_divide(
            total_arrivals, external_arrivals
        ),
        "repeat_attempt_share": _safe_divide(redial_arrivals, total_arrivals),
    }


def _validate_simulation_state(
    *,
    t: float,
    event: Optional[int],
    rates: Optional[np.ndarray],
    total_rate: Optional[float],
    B: int,
    RS: int,
    RL: int,
    waiting_count: int,
    service_count: int,
    capacity: int,
    require_positive_total_rate: bool,
) -> None:
    """Raise ValueError if the current stochastic state violates invariants."""

    Q = waiting_count + service_count
    state = {
        "Q": Q,
        "B": B,
        "RS": RS,
        "RL": RL,
        "waiting": waiting_count,
        "in_service": service_count,
        "capacity": capacity,
    }
    event_name = EVENT_NAMES[event] if event is not None and 0 <= event < len(EVENT_NAMES) else None
    prefix = f"Invalid simulation state at t={t}, event={event_name or event}"

    for name, value in state.items():
        if not math.isfinite(float(value)):
            raise ValueError(f"{prefix}: {name} is not finite; state={state}")
    if Q < 0 or B < 0 or RS < 0 or RL < 0 or waiting_count < 0:
        raise ValueError(f"{prefix}: negative state value; state={state}")
    if service_count > capacity:
        raise ValueError(f"{prefix}: in_service exceeds capacity; state={state}")

    if rates is not None:
        if not np.isfinite(rates).all():
            raise ValueError(f"{prefix}: non-finite event rate; rates={rates}")
        if (rates < 0).any():
            raise ValueError(f"{prefix}: negative event rate; rates={rates}")
    if total_rate is not None:
        if not math.isfinite(total_rate):
            raise ValueError(f"{prefix}: total_rate is not finite")
        if require_positive_total_rate and total_rate <= 0:
            raise ValueError(f"{prefix}: total_rate must be positive before sampling")


def simulate_one(params: SimulationParams, validate: bool = False) -> SimulationResult:
    """Run one Gillespie simulation of the SNAP call center model.

    Time averages and event statistics are collected after ``params.warmup``.
    Queue service is FCFS, while abandonment selects a uniformly random waiting
    caller, as implied by identical exponential abandonment clocks.
    Set ``validate=True`` to run invariant checks during the event loop.
    """

    _validate_params(params)
    # NumPy's Generator is the model's only randomness source, aiding reproducibility.
    rng = np.random.default_rng(params.seed)

    # B, RS, and RL are external pools that can generate future calls.
    B = params.b0
    RS = params.rs0
    RL = params.rl0
    # Up to c initial callers enter service immediately; the rest wait in queue.
    initial_in_service = min(params.q0, params.c)
    # in_service stores the service start time for each caller currently in service.
    in_service = [0.0] * initial_in_service
    # waiting_queue stores each waiting caller's queue entry time for wait metrics.
    waiting_queue = [0.0] * (params.q0 - initial_in_service)

    # counts records discrete event counts after warmup.
    counts = {
        "fresh_arrivals": 0,
        "recertification_arrivals": 0,
        "short_redial_arrivals": 0,
        "long_redial_arrivals": 0,
        "service_successes": 0,
        "service_failures": 0,
        "abandon_lost": 0,
        "abandon_short": 0,
        "abandon_long": 0,
    }
    # answered_waits stores waits for callers who eventually reach service.
    answered_waits: list[float] = []
    # abandoned_waits stores waits for callers who eventually abandon.
    abandoned_waits: list[float] = []
    # areas accumulates state-time integrals used to compute time averages.
    areas = {
        "Q": 0.0,
        "waiting": 0.0,
        "B": 0.0,
        "RS": 0.0,
        "RL": 0.0,
        "busy": 0.0,
    }

    # These min/max diagnostics help detect violations of state constraints.
    min_Q = params.q0
    min_B = B
    min_RS = RS
    min_RL = RL
    max_in_service = len(in_service)
    # Current simulation clock.
    t = 0.0

    def admit_caller(entry_time: float, event_time: float, collect: bool) -> None:
        """Put an arriving caller into service if possible, otherwise queue it.

        entry_time is when the caller entered the current queue; event_time is
        the current event time. Their difference is the caller's wait. For a
        fresh arrival they are usually equal, while callers moving from queue
        to service keep their earlier entry_time.
        """

        if len(in_service) < params.c:
            in_service.append(event_time)
            if collect:
                answered_waits.append(event_time - entry_time)
        else:
            waiting_queue.append(entry_time)

    def start_next_waiting(event_time: float, collect: bool) -> None:
        """Move the earliest waiting caller into service after a server frees up."""

        if len(waiting_queue) > 0 and len(in_service) < params.c:
            entry_time = waiting_queue.pop(0)
            in_service.append(event_time)
            if collect:
                answered_waits.append(event_time - entry_time)

    while t < params.T:
        # Current waiting and service counts determine all event rates in this step.
        n_waiting = len(waiting_queue)
        n_service = len(in_service)
        # Each rates entry corresponds to one possible event:
        # 0 fresh arrival;
        # 1 recertification arrival generated by B;
        # 2 short-redial arrival generated by RS;
        # 3 long-redial arrival generated by RL;
        # 4 waiting caller abandons and is lost;
        # 5 waiting caller abandons into RS;
        # 6 waiting caller abandons into RL;
        # 7 successful service completion;
        # 8 failed service completion;
        # 9 natural departure from pool B.
        rates = np.array(
            [
                params.lam,
                params.deltaB * B,
                params.deltaS * RS,
                params.deltaL * RL,
                params.thetaA * n_waiting,
                params.thetaS * n_waiting,
                params.thetaL * n_waiting,
                params.mu_plus * n_service,
                params.mu_minus * n_service,
                params.gamma * B,
            ],
            dtype=float,
        )
        # total_rate is the aggregate intensity of the next event.
        total_rate = float(rates.sum())
        if validate:
            _validate_simulation_state(
                t=t,
                event=None,
                rates=rates,
                total_rate=total_rate,
                B=B,
                RS=RS,
                RL=RL,
                waiting_count=n_waiting,
                service_count=n_service,
                capacity=params.c,
                require_positive_total_rate=total_rate > 0.0,
            )
        # Exponential waiting times are the standard CTMC/Gillespie simulation step.
        event_time = (
            params.T
            if total_rate == 0.0
            else t + rng.exponential(1.0 / total_rate)
        )
        # If the next event exceeds T, accumulate state integrals only up to T.
        interval_end = min(event_time, params.T)

        # Accumulate time averages only after warmup; earlier time only evolves state.
        observed_start = max(t, params.warmup)
        observed_dt = max(0.0, interval_end - observed_start)
        if observed_dt > 0:
            areas["Q"] += (n_waiting + n_service) * observed_dt
            areas["waiting"] += n_waiting * observed_dt
            areas["B"] += B * observed_dt
            areas["RS"] += RS * observed_dt
            areas["RL"] += RL * observed_dt
            areas["busy"] += n_service * observed_dt

        # Stop if no event can occur or if the next event is beyond the horizon.
        if event_time > params.T or total_rate == 0.0:
            t = params.T
            break

        t = event_time
        # collect controls whether the current event enters post-warmup statistics.
        collect = t >= params.warmup
        # Sample from cumulative rate intervals; the draw is always in [0, total_rate).
        event = sample_event(rates, total_rate, rng)

        if event == 0:  # Fresh arrival
            # External fresh arrival enters the system without changing B, RS, or RL.
            if collect:
                counts["fresh_arrivals"] += 1
            admit_caller(t, t, collect)
        elif event == 1:  # Recertification arrival
            # One individual in B generates a recertification call and leaves B.
            B -= 1
            if collect:
                counts["recertification_arrivals"] += 1
            admit_caller(t, t, collect)
        elif event == 2:  # Short-redial arrival
            # One short-redial individual returns, leaves RS, and enters the system.
            RS -= 1
            if collect:
                counts["short_redial_arrivals"] += 1
            admit_caller(t, t, collect)
        elif event == 3:  # Long-redial arrival
            # One long-redial individual returns, leaves RL, and enters the system.
            RL -= 1
            if collect:
                counts["long_redial_arrivals"] += 1
            admit_caller(t, t, collect)
        elif event in (4, 5, 6):  # Waiting-caller abandonment
            # Waiting callers have identical clocks, so choose the abandoner uniformly.
            abandoned_index = int(rng.integers(len(waiting_queue)))
            entry_time = waiting_queue.pop(abandoned_index)
            if collect:
                abandoned_waits.append(t - entry_time)
            if event == 4:
                # Lost abandonment: the caller does not enter any redial pool.
                if collect:
                    counts["abandon_lost"] += 1
            elif event == 5:
                # Short redial: the caller may return later at aggregate rate deltaS * RS.
                RS += 1
                if collect:
                    counts["abandon_short"] += 1
            else:
                # Long redial: the caller may return later at aggregate rate deltaL * RL.
                RL += 1
                if collect:
                    counts["abandon_long"] += 1
        elif event in (7, 8):  # Service completion
            # In-service callers have identical clocks, so choose the completer uniformly.
            completed_index = int(rng.integers(len(in_service)))
            in_service.pop(completed_index)
            if event == 7:
                # Successful service: the individual enters B.
                B += 1
                if collect:
                    counts["service_successes"] += 1
            else:
                # Failed service: the individual enters the long-redial pool RL.
                RL += 1
                if collect:
                    counts["service_failures"] += 1
            # When a server frees up, admit the next waiting caller under FCFS.
            start_next_waiting(t, collect)
        else:  # Enrolled departure
            # Natural departure from B without generating a call.
            B -= 1

        # Update diagnostics after each event to check nonnegativity and capacity.
        Q = len(waiting_queue) + len(in_service)
        min_Q = min(min_Q, Q)
        min_B = min(min_B, B)
        min_RS = min(min_RS, RS)
        min_RL = min(min_RL, RL)
        max_in_service = max(max_in_service, len(in_service))
        if validate:
            _validate_simulation_state(
                t=t,
                event=event,
                rates=None,
                total_rate=None,
                B=B,
                RS=RS,
                RL=RL,
                waiting_count=len(waiting_queue),
                service_count=len(in_service),
                capacity=params.c,
                require_positive_total_rate=False,
            )

    # Observation time used for averages and rates, excluding warmup.
    observation_time = params.T - params.warmup
    # Total arrivals are the four event types that enter the system.
    total_arrivals = sum(
        counts[name]
        for name in (
            "fresh_arrivals",
            "recertification_arrivals",
            "short_redial_arrivals",
            "long_redial_arrivals",
        )
    )
    # Total abandonments are the three abandonment routes.
    total_abandonments = sum(
        counts[name] for name in ("abandon_lost", "abandon_short", "abandon_long")
    )
    # Overall wait includes both answered and abandoned callers.
    all_waits = answered_waits + abandoned_waits

    def mean_minutes(values: list[float]) -> float:
        """Convert a list of model-day waits to an average in minutes."""

        return (
            (float(np.mean(values)) * MINUTES_PER_MODEL_DAY)
            if len(values) > 0
            else 0.0
        )

    result_values = {
        "total_arrivals": total_arrivals,
        "fresh_arrivals": counts["fresh_arrivals"],
        "recertification_arrivals": counts["recertification_arrivals"],
        "short_redial_arrivals": counts["short_redial_arrivals"],
        "long_redial_arrivals": counts["long_redial_arrivals"],
        "total_abandonments": total_abandonments,
    }
    repeat_attempt_proxies = compute_repeat_attempt_proxies(result_values)

    # Package event counts, time averages, wait metrics, and diagnostics.
    return SimulationResult(
        total_arrivals=total_arrivals,
        fresh_arrivals=counts["fresh_arrivals"],
        recertification_arrivals=counts["recertification_arrivals"],
        short_redial_arrivals=counts["short_redial_arrivals"],
        long_redial_arrivals=counts["long_redial_arrivals"],
        service_successes=counts["service_successes"],
        service_failures=counts["service_failures"],
        abandon_lost=counts["abandon_lost"],
        abandon_short=counts["abandon_short"],
        abandon_long=counts["abandon_long"],
        total_abandonments=total_abandonments,
        mean_Q=areas["Q"] / observation_time,
        mean_waiting=areas["waiting"] / observation_time,
        mean_B=areas["B"] / observation_time,
        mean_RS=areas["RS"] / observation_time,
        mean_RL=areas["RL"] / observation_time,
        utilization=(
            areas["busy"] / (params.c * observation_time) if params.c > 0 else 0.0
        ),
        average_wait_including_abandonments_minutes=mean_minutes(all_waits),
        average_speed_to_answer_minutes=mean_minutes(answered_waits),
        average_time_to_abandonment_minutes=mean_minutes(abandoned_waits),
        abandonment_fraction=(
            total_abandonments / total_arrivals if total_arrivals > 0 else 0.0
        ),
        procedural_denial_rate_per_model_day=counts["abandon_lost"] / observation_time,
        total_arrival_rate_per_model_day=total_arrivals / observation_time,
        effective_arrival_rate_per_model_day=(total_arrivals - total_abandonments)
        / observation_time,
        returning_call_rate_per_model_day=(
            counts["recertification_arrivals"]
            + counts["short_redial_arrivals"]
            + counts["long_redial_arrivals"]
        )
        / observation_time,
        final_Q=len(waiting_queue) + len(in_service),
        final_waiting=len(waiting_queue),
        final_in_service=len(in_service),
        final_B=B,
        final_RS=RS,
        final_RL=RL,
        min_Q=min_Q,
        min_B=min_B,
        min_RS=min_RS,
        min_RL=min_RL,
        max_in_service=max_in_service,
        **repeat_attempt_proxies,
    )


def run_replications(
    params: SimulationParams, n_replications: int, validate: bool = False
) -> pd.DataFrame:
    """Run independent replications and return one summary row per run.

    n_replications is the number of independent repeated experiments. The
    function derives n_replications child seeds from params.seed so that runs
    are independent while the full replication table remains reproducible for
    the same original seed.
    """

    # The replication count must be positive; bool is excluded despite being an int.
    if not isinstance(n_replications, (int, np.integer)) or isinstance(
        n_replications, bool
    ):
        raise ValueError("n_replications must be an integer")
    if n_replications <= 0:
        raise ValueError("n_replications must be positive")

    # SeedSequence.spawn creates statistically independent child random sequences.
    seed_sequence = np.random.SeedSequence(params.seed)
    child_sequences = seed_sequence.spawn(n_replications)
    rows = []
    for replication, child_sequence in enumerate(child_sequences):
        # Convert the child sequence into an integer seed accepted by simulate_one.
        replication_seed = int(child_sequence.generate_state(1, dtype=np.uint64)[0])
        result = simulate_one(replace(params, seed=replication_seed), validate=validate)
        # Each row keeps the replication id, actual seed, and all result fields.
        row = {"replication": replication, "seed": replication_seed}
        row.update(result.to_dict())
        rows.append(row)

    return pd.DataFrame(rows)
