"""Event-driven stochastic simulator for the SNAP call center model.

This module implements a continuous-time, event-driven stochastic simulator.
At each simulation step, it samples the time of the next event from the total
event rate, then samples the event type in proportion to each event's rate.

The model's base time unit is one model day. Wait-time outputs are converted
to minutes with ``MINUTES_PER_MODEL_DAY``.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass, replace
import math
from typing import Optional

import numpy as np
import pandas as pd


# Number of minutes represented by one model day; 540 minutes is a 9-hour day.
MINUTES_PER_MODEL_DAY = 540.0

EVENT_NAMES = (
    "fresh_arrival",
    "recertification_arrival",
    "short_redial_arrival",
    "long_redial_arrival",
    "abandon_lost",
    "abandon_short",
    "abandon_long",
    "service_success",
    "service_failure",
    "enrolled_departure",
)


@dataclass(frozen=True)
class SimulationParams:
    """Inputs for one continuous-time simulation replication.

    These parameters define the exogenous conditions for one independent
    replication. All rate parameters are expressed per model day; for example,
    ``lam=20`` means an average of 20 fresh arrivals per model day. Queue and
    population parameters are measured as counts of callers or individuals.
    """

    # Total simulation horizon. The event loop runs until simulation time reaches T.
    T: float
    # Warmup period. Events before warmup affect state evolution but not statistics.
    warmup: float
    # Number of servers/agents and the maximum number of concurrent services.
    c: int

    # Exogenous arrival rate of new callers.
    lam: float
    # Successful service completion rate for each caller in service; success enters B.
    mu_plus: float
    # Failed service completion rate for each caller in service; failure enters RL.
    mu_minus: float
    # Abandonment-and-loss rate for each waiting caller.
    thetaA: float
    # Abandonment rate into the short-redial pool RS for each waiting caller.
    thetaS: float
    # Abandonment rate into the long-redial pool RL for each waiting caller.
    thetaL: float
    # Recertification-call rate generated by each individual in pool B.
    deltaB: float
    # Return-call rate for each individual in the short-redial pool RS.
    deltaS: float
    # Return-call rate for each individual in the long-redial pool RL.
    deltaL: float
    # Natural departure rate for each individual in pool B.
    gamma: float

    # Initial number of callers in the system; up to min(q0, c) start in service.
    q0: int = 0
    # Initial size of pool B.
    b0: int = 0
    # Initial size of the short-redial pool RS.
    rs0: int = 0
    # Initial size of the long-redial pool RL.
    rl0: int = 0
    # Random seed. The same seed produces a reproducible single replication.
    seed: Optional[int] = None
    # Fresh-arrival process. "constant" preserves the historical lam behavior.
    arrival_process: str = "constant"
    # Baseline fresh-arrival rate for non-stationary arrivals; defaults to lam.
    lambda0: Optional[float] = None
    # Sinusoidal relative amplitude A in lambda0 * (1 + A sin(...)).
    arrival_amplitude: float = 0.0
    # Sinusoidal period in model days, matching the simulator's base time unit.
    arrival_period: float = 1.0
    # Sinusoidal phase shift in radians.
    arrival_phase: float = 0.0


@dataclass
class Caller:
    """Caller-level state needed for waits and enrollment-attempt counts."""

    queue_entry_time: float
    caller_id: int = -1
    first_arrival_time: float | None = None
    service_start_time: float | None = None
    completion_time: float | None = None
    exit_time: float | None = None
    attempt_count: int = 0
    source_type: str = "fresh"
    current_location: str = "queue"

    def __post_init__(self) -> None:
        if self.first_arrival_time is None:
            self.first_arrival_time = self.queue_entry_time

    def is_cohort_member(
        self, cohort_start: float | None, cohort_end: float | None
    ) -> bool:
        """Return whether this caller's first arrival lies in the target cohort."""

        return (
            cohort_start is not None
            and cohort_end is not None
            and cohort_start <= float(self.first_arrival_time) < cohort_end
        )


@dataclass(frozen=True)
class SimulationResult:
    """Summary statistics and invariant diagnostics for one replication.

    Count fields include only events after warmup. State fields, such as
    final_Q and min_B, describe states observed at the end of or during the
    full simulation path.
    """

    # Total arrivals after warmup, including fresh, recertification, and redial calls.
    total_arrivals: int
    # Number of exogenous fresh arrivals.
    fresh_arrivals: int
    # Number of recertification arrivals generated by pool B.
    recertification_arrivals: int
    # Number of return calls from the short-redial pool RS.
    short_redial_arrivals: int
    # Number of return calls from the long-redial pool RL.
    long_redial_arrivals: int
    # Number of successful service completions; successful callers enter B.
    service_successes: int
    # Number of failed service completions; failed callers enter RL.
    service_failures: int
    # Number of waiting callers who abandon and leave the system.
    abandon_lost: int
    # Number of waiting callers who abandon into the short-redial pool RS.
    abandon_short: int
    # Number of waiting callers who abandon into the long-redial pool RL.
    abandon_long: int
    # Total number of abandonment events across all abandonment routes.
    total_abandonments: int

    # Time-average total system occupancy Q: waiting callers plus callers in service.
    mean_Q: float
    # Time-average waiting queue length.
    mean_waiting: float
    # Time-average size of pool B.
    mean_B: float
    # Time-average size of the short-redial pool RS.
    mean_RS: float
    # Time-average size of the long-redial pool RL.
    mean_RL: float
    # Server utilization: busy server time divided by c * observation_time.
    utilization: float

    # Mean wait for all callers who leave waiting, including answered and abandoned.
    average_wait_including_abandonments_minutes: float
    # Average speed to answer among callers who reach service, in minutes.
    average_speed_to_answer_minutes: float
    # Mean time to abandonment among callers who abandon, in minutes.
    average_time_to_abandonment_minutes: float
    # Abandonment fraction: total_abandonments / total_arrivals.
    abandonment_fraction: float
    # Procedural denial rate, represented here by abandon-and-lost events per model day.
    procedural_denial_rate_per_model_day: float
    # Total arrival rate after warmup, measured per model day.
    total_arrival_rate_per_model_day: float
    # Effective arrival rate: non-abandoned arrivals divided by observation time.
    effective_arrival_rate_per_model_day: float
    # Returning-call rate from recertification, short-redial, and long-redial arrivals.
    returning_call_rate_per_model_day: float

    # Total number of callers in the system at the end of the simulation.
    final_Q: int
    # Waiting queue length at the end of the simulation.
    final_waiting: int
    # Number of callers in service at the end of the simulation.
    final_in_service: int
    # Size of pool B at the end of the simulation.
    final_B: int
    # Size of the short-redial pool RS at the end of the simulation.
    final_RS: int
    # Size of the long-redial pool RL at the end of the simulation.
    final_RL: int
    # Minimum Q observed during the simulation, used as a diagnostic.
    min_Q: int
    # Minimum B observed during the simulation.
    min_B: int
    # Minimum RS observed during the simulation.
    min_RS: int
    # Minimum RL observed during the simulation.
    min_RL: int
    # Maximum number of callers simultaneously in service; should not exceed c.
    max_in_service: int
    # Aggregate proxy: abandonments divided by fresh arrivals.
    abandonments_per_fresh_arrival: float
    # Aggregate proxy: abandonments divided by fresh plus recertification arrivals.
    abandonments_per_external_arrival: float
    # Aggregate proxy: redial arrivals divided by fresh arrivals.
    redial_arrivals_per_fresh_arrival: float
    # Aggregate proxy: redial arrivals divided by fresh plus recertification arrivals.
    redial_arrivals_per_external_arrival: float
    # Aggregate proxy: all attempts divided by fresh arrivals.
    total_attempts_per_fresh_arrival: float
    # Aggregate proxy: all attempts divided by fresh plus recertification arrivals.
    total_attempts_per_external_arrival: float
    # Aggregate proxy: redial arrivals divided by all arrivals.
    repeat_attempt_share: float
    # Mean retry count before successful enrollment; 0 means success on first call.
    mean_attempts_before_enrollment: float
    # Median retry count before successful enrollment.
    median_attempts_before_enrollment: float
    # 90th percentile retry count before successful enrollment.
    p90_attempts_before_enrollment: float
    # 95th percentile retry count before successful enrollment.
    p95_attempts_before_enrollment: float
    # Maximum retry count observed before successful enrollment.
    max_attempts_before_enrollment: int
    # Number of post-warmup successful enrollments with attempt records.
    num_completed_enrollments_with_attempt_records: int

    def to_dict(self) -> dict[str, int | float]:
        """Return the result as a flat dictionary suitable for a DataFrame row."""

        return asdict(self)


def _validate_params(params: SimulationParams) -> None:
    """Validate model parameters before running stochastic dynamics.

    Validation covers three groups:
    1. continuous-time and rate parameters must be finite real values;
    2. the time range must be valid, with warmup shorter than T;
    3. population, capacity, and seed fields must be nonnegative integers.
    """

    # These fields may be int or float, but not inf, -inf, or nan.
    real_fields = (
        "T",
        "warmup",
        "lam",
        "mu_plus",
        "mu_minus",
        "thetaA",
        "thetaS",
        "thetaL",
        "deltaB",
        "deltaS",
        "deltaL",
        "gamma",
        "arrival_amplitude",
        "arrival_period",
        "arrival_phase",
    )
    for name in real_fields:
        value = getattr(params, name)
        if not math.isfinite(value):
            raise ValueError(f"{name} must be finite")

    # T is the simulation endpoint and must be positive; warmup is discarded time.
    if params.T <= 0:
        raise ValueError("T must be positive")
    if params.warmup < 0 or params.warmup >= params.T:
        raise ValueError("warmup must satisfy 0 <= warmup < T")

    # Apart from T, warmup, arrival_amplitude, and arrival_phase, real fields are rates.
    for name in real_fields[2:14]:
        if getattr(params, name) < 0:
            raise ValueError(f"{name} must be nonnegative")
    if params.lambda0 is not None:
        if not math.isfinite(params.lambda0):
            raise ValueError("lambda0 must be finite")
        if params.lambda0 < 0:
            raise ValueError("lambda0 must be nonnegative")
    if params.arrival_process not in ("constant", "sinusoidal"):
        raise ValueError("arrival_process must be 'constant' or 'sinusoidal'")
    if params.arrival_amplitude < 0 or params.arrival_amplitude > 1:
        raise ValueError("arrival_amplitude must satisfy 0 <= amplitude <= 1")
    if params.arrival_period <= 0:
        raise ValueError("arrival_period must be positive")

    # c, q0, b0, rs0, and rl0 are capacities or population counts.
    integer_fields = ("c", "q0", "b0", "rs0", "rl0")
    for name in integer_fields:
        value = getattr(params, name)
        if not isinstance(value, (int, np.integer)) or isinstance(value, bool):
            raise ValueError(f"{name} must be an integer")
        if value < 0:
            raise ValueError(f"{name} must be nonnegative")

    # seed may be None; otherwise it must be a nonnegative integer, excluding bool.
    if params.seed is not None:
        if not isinstance(params.seed, (int, np.integer)) or isinstance(params.seed, bool):
            raise ValueError("seed must be an integer or None")
        if params.seed < 0:
            raise ValueError("seed must be nonnegative")


def _safe_divide(numerator: float, denominator: float) -> float:
    """Return numerator / denominator, using 0.0 when the denominator is zero."""

    return float(numerator / denominator) if denominator != 0 else 0.0


def _base_arrival_rate(params: SimulationParams) -> float:
    """Return lambda0 when supplied, otherwise the historical lam parameter."""

    return params.lam if params.lambda0 is None else params.lambda0


def arrival_rate_at(t: float, params: SimulationParams) -> float:
    """Return the external fresh-arrival rate at time t.

    Time is measured in model days, the same unit used by the simulator. The
    sinusoidal process models predictable within-horizon load variation around
    ``lambda0``; ``arrival_amplitude`` is restricted to [0, 1] by validation so
    the rate is never negative.
    """

    _validate_params(params)
    if params.arrival_process == "constant":
        return float(params.lam)
    rate = _base_arrival_rate(params) * (
        1.0
        + params.arrival_amplitude
        * math.sin(2.0 * math.pi * t / params.arrival_period + params.arrival_phase)
    )
    return float(rate)


def arrival_rate_upper_bound(
    params: SimulationParams, horizon: float | None = None
) -> float:
    """Return a dominating fresh-arrival rate for NHPP thinning."""

    del horizon
    _validate_params(params)
    if params.arrival_process == "constant":
        return float(params.lam)
    return float(_base_arrival_rate(params) * (1.0 + params.arrival_amplitude))


def generate_arrival_times(
    params: SimulationParams, horizon: float, rng: np.random.Generator
):
    """Yield fresh-arrival times using Lewis-Shedler thinning for NHPP arrivals."""

    _validate_params(params)
    if horizon <= 0:
        raise ValueError("horizon must be positive")
    lambda_max = arrival_rate_upper_bound(params, horizon)
    if lambda_max == 0.0:
        return
    t = 0.0
    while t < horizon:
        t += rng.exponential(1.0 / lambda_max)
        if t > horizon:
            break
        if rng.random() <= arrival_rate_at(t, params) / lambda_max:
            yield t


def sample_event(rates: np.ndarray, total_rate: float, rng: np.random.Generator) -> int:
    """Sample one event index from nonnegative rates.

    The draw is in [0, total_rate), so ``searchsorted(..., side="right")`` returns
    an index in the valid range whenever rates are nonnegative and total_rate > 0.
    """

    draw = rng.random() * total_rate
    return int(np.searchsorted(np.cumsum(rates), draw, side="right"))


def compute_repeat_attempt_proxies(result_or_mapping) -> dict[str, float]:
    """Compute aggregate proxy metrics for repeated system attempts.

    These are flow-ratio approximations based on aggregate counts. They do not
    reconstruct caller-level histories or exact per-caller attempt counts.
    """

    def get_value(name: str) -> float:
        if isinstance(result_or_mapping, dict):
            return float(result_or_mapping.get(name, 0.0))
        return float(getattr(result_or_mapping, name, 0.0))

    fresh_arrivals = get_value("fresh_arrivals")
    recertification_arrivals = get_value("recertification_arrivals")
    short_redial_arrivals = get_value("short_redial_arrivals")
    long_redial_arrivals = get_value("long_redial_arrivals")
    total_abandonments = get_value("total_abandonments")
    total_arrivals = get_value("total_arrivals")

    redial_arrivals = short_redial_arrivals + long_redial_arrivals
    external_arrivals = fresh_arrivals + recertification_arrivals

    return {
        "abandonments_per_fresh_arrival": _safe_divide(
            total_abandonments, fresh_arrivals
        ),
        "abandonments_per_external_arrival": _safe_divide(
            total_abandonments, external_arrivals
        ),
        "redial_arrivals_per_fresh_arrival": _safe_divide(
            redial_arrivals, fresh_arrivals
        ),
        "redial_arrivals_per_external_arrival": _safe_divide(
            redial_arrivals, external_arrivals
        ),
        "total_attempts_per_fresh_arrival": _safe_divide(
            total_arrivals, fresh_arrivals
        ),
        "total_attempts_per_external_arrival": _safe_divide(
            total_arrivals, external_arrivals
        ),
        "repeat_attempt_share": _safe_divide(redial_arrivals, total_arrivals),
    }


def summarize_attempt_records(records: list[int]) -> dict[str, int | float]:
    """Summarize completed enrollment attempt counts.

    attempt_count=0 means the caller enrolled on the initial call without a
    return from a redial orbit during that enrollment episode.
    """

    if len(records) == 0:
        return {
            "mean_attempts_before_enrollment": 0.0,
            "median_attempts_before_enrollment": 0.0,
            "p90_attempts_before_enrollment": 0.0,
            "p95_attempts_before_enrollment": 0.0,
            "max_attempts_before_enrollment": 0,
            "num_completed_enrollments_with_attempt_records": 0,
        }
    values = np.asarray(records, dtype=float)
    return {
        "mean_attempts_before_enrollment": float(np.mean(values)),
        "median_attempts_before_enrollment": float(np.median(values)),
        "p90_attempts_before_enrollment": float(np.percentile(values, 90)),
        "p95_attempts_before_enrollment": float(np.percentile(values, 95)),
        "max_attempts_before_enrollment": int(np.max(values)),
        "num_completed_enrollments_with_attempt_records": int(len(records)),
    }


def attempt_distribution_table(records: list[int]) -> pd.DataFrame:
    """Return attempt_count,num_callers,fraction for completed enrollments."""

    counts = Counter(records)
    total = sum(counts.values())
    rows = []
    for attempt_count in sorted(counts):
        num_callers = counts[attempt_count]
        rows.append(
            {
                "attempt_count": attempt_count,
                "num_callers": num_callers,
                "fraction": _safe_divide(num_callers, total),
            }
        )
    return pd.DataFrame(rows, columns=["attempt_count", "num_callers", "fraction"])


def _numeric_summary(values: list[float]) -> dict[str, float]:
    """Return mean, median, p90, p95, and max with NaNs for empty input."""

    if len(values) == 0:
        return {
            "mean": float("nan"),
            "median": float("nan"),
            "p90": float("nan"),
            "p95": float("nan"),
            "max": float("nan"),
        }
    array = np.asarray(values, dtype=float)
    return {
        "mean": float(np.mean(array)),
        "median": float(np.median(array)),
        "p90": float(np.percentile(array, 90)),
        "p95": float(np.percentile(array, 95)),
        "max": float(np.max(array)),
    }


def cohort_summary_table(
    caller_records: pd.DataFrame,
    unfinished_callers: pd.DataFrame,
    *,
    cohort_start: float | None,
    cohort_end: float | None,
    horizon: float,
) -> pd.DataFrame:
    """Summarize completion and burden metrics for one first-arrival cohort."""

    if cohort_start is None or cohort_end is None:
        number_of_cohort_callers = 0
        completed = caller_records.iloc[0:0]
    else:
        completed = caller_records[caller_records["cohort_member"]]
        number_of_cohort_callers = int(len(completed) + len(unfinished_callers))
    number_of_completed = int(len(completed))
    number_of_unfinished = int(number_of_cohort_callers - number_of_completed)
    attempt_stats = _numeric_summary(completed["attempt_count"].tolist())
    time_stats = _numeric_summary(completed["time_to_enrollment"].tolist())

    return pd.DataFrame(
        [
            {
                "cohort_start": cohort_start,
                "cohort_end": cohort_end,
                "horizon": horizon,
                "number_of_cohort_callers": number_of_cohort_callers,
                "number_of_completed_cohort_callers": number_of_completed,
                "number_of_unfinished_cohort_callers": number_of_unfinished,
                "cohort_completion_rate": (
                    number_of_completed / number_of_cohort_callers
                    if number_of_cohort_callers > 0
                    else float("nan")
                ),
                "mean_attempts": attempt_stats["mean"],
                "median_attempts": attempt_stats["median"],
                "p90_attempts": attempt_stats["p90"],
                "p95_attempts": attempt_stats["p95"],
                "mean_time_to_enrollment": time_stats["mean"],
                "median_time_to_enrollment": time_stats["median"],
                "p90_time_to_enrollment": time_stats["p90"],
                "p95_time_to_enrollment": time_stats["p95"],
            }
        ]
    )


def caller_attempt_distribution_table(caller_records: pd.DataFrame) -> pd.DataFrame:
    """Return attempt_count,count,proportion for caller-level records."""

    if len(caller_records) == 0:
        return pd.DataFrame(columns=["attempt_count", "count", "proportion"])
    counts = Counter(int(value) for value in caller_records["attempt_count"])
    total = sum(counts.values())
    return pd.DataFrame(
        [
            {
                "attempt_count": attempt_count,
                "count": count,
                "proportion": _safe_divide(count, total),
            }
            for attempt_count, count in sorted(counts.items())
        ],
        columns=["attempt_count", "count", "proportion"],
    )


def time_to_enrollment_summary_table(caller_records: pd.DataFrame) -> pd.DataFrame:
    """Return mean, median, p90, p95, and max time-to-enrollment for records."""

    stats = _numeric_summary(caller_records["time_to_enrollment"].tolist())
    return pd.DataFrame([stats], columns=["mean", "median", "p90", "p95", "max"])


def _validate_simulation_state(
    *,
    t: float,
    event: Optional[int],
    rates: Optional[np.ndarray],
    total_rate: Optional[float],
    B: int,
    RS: int,
    RL: int,
    waiting_count: int,
    service_count: int,
    capacity: int,
    require_positive_total_rate: bool,
) -> None:
    """Raise ValueError if the current stochastic state violates invariants."""

    Q = waiting_count + service_count
    state = {
        "Q": Q,
        "B": B,
        "RS": RS,
        "RL": RL,
        "waiting": waiting_count,
        "in_service": service_count,
        "capacity": capacity,
    }
    event_name = EVENT_NAMES[event] if event is not None and 0 <= event < len(EVENT_NAMES) else None
    prefix = f"Invalid simulation state at t={t}, event={event_name or event}"

    for name, value in state.items():
        if not math.isfinite(float(value)):
            raise ValueError(f"{prefix}: {name} is not finite; state={state}")
    if Q < 0 or B < 0 or RS < 0 or RL < 0 or waiting_count < 0:
        raise ValueError(f"{prefix}: negative state value; state={state}")
    if service_count > capacity:
        raise ValueError(f"{prefix}: in_service exceeds capacity; state={state}")

    if rates is not None:
        if not np.isfinite(rates).all():
            raise ValueError(f"{prefix}: non-finite event rate; rates={rates}")
        if (rates < 0).any():
            raise ValueError(f"{prefix}: negative event rate; rates={rates}")
    if total_rate is not None:
        if not math.isfinite(total_rate):
            raise ValueError(f"{prefix}: total_rate is not finite")
        if require_positive_total_rate and total_rate <= 0:
            raise ValueError(f"{prefix}: total_rate must be positive before sampling")


def simulate_one(
    params: SimulationParams,
    validate: bool = False,
    return_attempt_records: bool = False,
    return_caller_records: bool = False,
    return_end_state_distribution: bool = False,
    return_cohort_summary: bool = False,
    cohort_start: float | None = None,
    cohort_end: float | None = None,
    dynamic_horizon: bool = False,
    post_clearance_buffer: float = 20.0,
    max_dynamic_horizon: float | None = None,
    max_events: int | None = None,
    record_path: bool = False,
    record_dt: float | None = None,
) -> (
    SimulationResult
    | tuple[SimulationResult, list[int]]
    | tuple[SimulationResult, pd.DataFrame]
    | tuple[SimulationResult, list[int], pd.DataFrame]
):
    """Run one Gillespie simulation of the SNAP call center model.

    Time averages and event statistics are collected after ``params.warmup``.
    Queue service is FCFS, while abandonment selects a uniformly random waiting
    caller, as implied by identical exponential abandonment clocks.
    Set ``validate=True`` to run invariant checks during the event loop.
    """

    _validate_params(params)
    if (cohort_start is None) != (cohort_end is None):
        raise ValueError("cohort_start and cohort_end must be provided together")
    if cohort_start is not None and cohort_end is not None:
        if not math.isfinite(cohort_start) or not math.isfinite(cohort_end):
            raise ValueError("cohort_start and cohort_end must be finite")
        if cohort_start >= cohort_end:
            raise ValueError("cohort_start must be less than cohort_end")
    if dynamic_horizon:
        if cohort_start is None or cohort_end is None:
            raise ValueError("dynamic_horizon requires cohort_start and cohort_end")
        if not math.isfinite(post_clearance_buffer) or post_clearance_buffer < 0:
            raise ValueError("post_clearance_buffer must be finite and nonnegative")
        if max_dynamic_horizon is not None:
            if not math.isfinite(max_dynamic_horizon) or max_dynamic_horizon <= 0:
                raise ValueError("max_dynamic_horizon must be positive and finite")
            if max_dynamic_horizon <= cohort_end:
                raise ValueError("max_dynamic_horizon must be greater than cohort_end")
        if max_events is not None:
            if not isinstance(max_events, (int, np.integer)) or isinstance(
                max_events, bool
            ):
                raise ValueError("max_events must be an integer or None")
            if max_events <= 0:
                raise ValueError("max_events must be positive")
    simulation_limit = (
        float(max_dynamic_horizon)
        if dynamic_horizon and max_dynamic_horizon is not None
        else float(params.T)
    )
    # NumPy's Generator is the model's only randomness source, aiding reproducibility.
    rng = np.random.default_rng(params.seed)

    # B, RS, and RL are external pools that can generate future calls.
    B = params.b0
    next_caller_id = 0
    all_callers: dict[int, Caller] = {}
    completed_caller_records: list[dict[str, int | float | bool]] = []
    cohort_size_collected = 0
    cohort_unfinished_live = 0

    def make_caller(
        *,
        event_time: float,
        source_type: str,
        attempt_count: int = 0,
        location: str = "queue",
    ) -> Caller:
        """Create and register a caller/person entering the tracked system."""

        nonlocal next_caller_id
        nonlocal cohort_size_collected, cohort_unfinished_live
        caller = Caller(
            queue_entry_time=event_time,
            caller_id=next_caller_id,
            first_arrival_time=event_time,
            attempt_count=attempt_count,
            source_type=source_type,
            current_location=location,
        )
        all_callers[caller.caller_id] = caller
        if caller.is_cohort_member(cohort_start, cohort_end):
            cohort_size_collected += 1
            cohort_unfinished_live += 1
        next_caller_id += 1
        return caller

    short_orbit = [
        make_caller(
            event_time=0.0,
            source_type="initial_short_orbit",
            attempt_count=1,
            location="short_orbit",
        )
        for _ in range(params.rs0)
    ]
    long_orbit = [
        make_caller(
            event_time=0.0,
            source_type="initial_long_orbit",
            attempt_count=1,
            location="long_orbit",
        )
        for _ in range(params.rl0)
    ]
    # Up to c initial callers enter service immediately; the rest wait in queue.
    initial_in_service = min(params.q0, params.c)
    # in_service stores caller records for callers currently being served.
    in_service = [
        make_caller(
            event_time=0.0,
            source_type="initial",
            attempt_count=0,
            location="service",
        )
        for _ in range(initial_in_service)
    ]
    for caller in in_service:
        caller.service_start_time = 0.0
    # waiting_queue is FIFO and stores caller records for callers waiting.
    waiting_queue = [
        make_caller(
            event_time=0.0,
            source_type="initial",
            attempt_count=0,
            location="queue",
        )
        for _ in range(params.q0 - initial_in_service)
    ]

    # counts records discrete event counts after warmup.
    counts = {
        "fresh_arrivals": 0,
        "recertification_arrivals": 0,
        "short_redial_arrivals": 0,
        "long_redial_arrivals": 0,
        "service_successes": 0,
        "service_failures": 0,
        "abandon_lost": 0,
        "abandon_short": 0,
        "abandon_long": 0,
    }
    # answered_waits stores waits for callers who eventually reach service.
    answered_waits: list[float] = []
    # abandoned_waits stores waits for callers who eventually abandon.
    abandoned_waits: list[float] = []
    # Completed enrollment episode attempt records, collected after warmup.
    completed_attempt_records: list[int] = []
    # areas accumulates state-time integrals used to compute time averages.
    areas = {
        "Q": 0.0,
        "waiting": 0.0,
        "B": 0.0,
        "RS": 0.0,
        "RL": 0.0,
        "busy": 0.0,
    }

    # These min/max diagnostics help detect violations of state constraints.
    min_Q = params.q0
    min_B = B
    min_RS = len(short_orbit)
    min_RL = len(long_orbit)
    max_in_service = len(in_service)
    # Current simulation clock.
    t = 0.0
    events_processed = 0
    dynamic_stop_time: float | None = None
    cohort_clearance_time: float | None = None
    termination_reason = "fixed_horizon"
    dynamic_horizon_success = False
    path_rows: list[dict[str, float | int]] = []
    if record_path:
        if record_dt is None:
            record_dt = simulation_limit / 500.0
        if record_dt <= 0 or not math.isfinite(record_dt):
            raise ValueError("record_dt must be positive and finite")
        next_record_t = 0.0
    if params.arrival_process == "sinusoidal":
        fresh_arrival_times = list(generate_arrival_times(params, simulation_limit, rng))
    else:
        fresh_arrival_times = []
    next_fresh_index = 0

    def orbit_count(orbit: list[Caller]) -> int:
        """Return the number of callers currently held in an orbit."""

        return len(orbit)

    def pop_orbit_caller(orbit: list[Caller], source_type: str) -> Caller:
        """Sample and remove one caller from an orbit."""

        orbit_index = int(rng.integers(len(orbit)))
        caller = orbit.pop(orbit_index)
        caller.queue_entry_time = t
        caller.service_start_time = None
        caller.source_type = source_type
        caller.current_location = "queue"
        return caller

    def add_to_orbit(caller: Caller, orbit: list[Caller], location: str) -> None:
        """Move a caller into an orbit after an unsuccessful call attempt."""

        caller.attempt_count += 1
        caller.service_start_time = None
        caller.current_location = location
        orbit.append(caller)

    def admit_caller(caller: Caller, event_time: float, collect: bool) -> None:
        """Put an arriving caller into service if possible, otherwise queue it.

        caller.queue_entry_time is when the caller entered the current queue.
        event_time is the current event time. Their difference is the caller's
        wait. Fresh arrivals and orbit returns usually enter with queue entry
        time equal to the current event time.
        """

        if len(in_service) < params.c:
            caller.service_start_time = event_time
            caller.current_location = "service"
            in_service.append(caller)
            if collect:
                answered_waits.append(event_time - caller.queue_entry_time)
        else:
            caller.current_location = "queue"
            waiting_queue.append(caller)

    def start_next_waiting(event_time: float, collect: bool) -> None:
        """Move the earliest waiting caller into service after a server frees up."""

        if len(waiting_queue) > 0 and len(in_service) < params.c:
            caller = waiting_queue.pop(0)
            caller.service_start_time = event_time
            caller.current_location = "service"
            in_service.append(caller)
            if collect:
                answered_waits.append(event_time - caller.queue_entry_time)

    def cohort_callers() -> list[Caller]:
        """Return all callers whose first arrival lies in the cohort window."""

        return [
            caller
            for caller in all_callers.values()
            if caller.is_cohort_member(cohort_start, cohort_end)
        ]

    def unfinished_cohort_count() -> int:
        """Return cohort callers without a terminal completion or exit time."""

        return sum(
            1
            for caller in cohort_callers()
            if caller.completion_time is None and caller.exit_time is None
        )

    while t < simulation_limit:
        current_stop_time = dynamic_stop_time or simulation_limit
        # Current waiting and service counts determine all event rates in this step.
        n_waiting = len(waiting_queue)
        n_service = len(in_service)
        RS = orbit_count(short_orbit)
        RL = orbit_count(long_orbit)
        # Each rates entry corresponds to one possible event:
        # 0 fresh arrival;
        # 1 recertification arrival generated by B;
        # 2 short-redial arrival generated by RS;
        # 3 long-redial arrival generated by RL;
        # 4 waiting caller abandons and is lost;
        # 5 waiting caller abandons into RS;
        # 6 waiting caller abandons into RL;
        # 7 successful service completion;
        # 8 failed service completion;
        # 9 natural departure from pool B.
        rates = np.array(
            [
                params.lam if params.arrival_process == "constant" else 0.0,
                params.deltaB * B,
                params.deltaS * RS,
                params.deltaL * RL,
                params.thetaA * n_waiting,
                params.thetaS * n_waiting,
                params.thetaL * n_waiting,
                params.mu_plus * n_service,
                params.mu_minus * n_service,
                params.gamma * B,
            ],
            dtype=float,
        )
        # total_rate is the aggregate intensity of the next event.
        total_rate = float(rates.sum())
        if validate:
            _validate_simulation_state(
                t=t,
                event=None,
                rates=rates,
                total_rate=total_rate,
                B=B,
                RS=RS,
                RL=RL,
                waiting_count=n_waiting,
                service_count=n_service,
                capacity=params.c,
                require_positive_total_rate=total_rate > 0.0,
            )
        # Exponential waiting times are the standard CTMC/Gillespie simulation step.
        endogenous_event_time = (
            current_stop_time
            if total_rate == 0.0
            else t + rng.exponential(1.0 / total_rate)
        )
        next_fresh_time = (
            fresh_arrival_times[next_fresh_index]
            if next_fresh_index < len(fresh_arrival_times)
            else math.inf
        )
        event_time = min(endogenous_event_time, next_fresh_time)
        # If the next event exceeds T, accumulate state integrals only up to T.
        interval_end = min(event_time, current_stop_time)
        if record_path:
            while next_record_t <= interval_end:
                path_rows.append(
                    {
                        "t": next_record_t,
                        "Q": n_waiting + n_service,
                        "B": B,
                        "RS": RS,
                        "RL": RL,
                    }
                )
                next_record_t += float(record_dt)

        # Accumulate time averages only after warmup; earlier time only evolves state.
        observed_start = max(t, params.warmup)
        observed_dt = max(0.0, interval_end - observed_start)
        if observed_dt > 0:
            areas["Q"] += (n_waiting + n_service) * observed_dt
            areas["waiting"] += n_waiting * observed_dt
            areas["B"] += B * observed_dt
            areas["RS"] += RS * observed_dt
            areas["RL"] += RL * observed_dt
            areas["busy"] += n_service * observed_dt

        # Stop if no event can occur or if the next event is beyond the horizon.
        fresh_event_due = (
            params.arrival_process == "sinusoidal"
            and next_fresh_index < len(fresh_arrival_times)
            and next_fresh_time <= endogenous_event_time
            and next_fresh_time < current_stop_time
        )
        endogenous_event_due = (
            endogenous_event_time <= next_fresh_time
            and endogenous_event_time < current_stop_time
            and total_rate > 0.0
        )
        if not fresh_event_due and not endogenous_event_due:
            t = current_stop_time
            if dynamic_horizon:
                if dynamic_stop_time is not None:
                    termination_reason = "cohort_cleared_buffer_elapsed"
                elif t >= simulation_limit:
                    termination_reason = "max_dynamic_horizon"
            else:
                termination_reason = "fixed_horizon"
            break

        t = event_time
        events_processed += 1
        # collect controls whether the current event enters post-warmup statistics.
        collect = t >= params.warmup
        if fresh_event_due:
            event = 0
            next_fresh_index += 1
        else:
            # Sample from cumulative rate intervals; the draw is always in [0, total_rate).
            event = sample_event(rates, total_rate, rng)

        if event == 0:  # Fresh arrival
            # External fresh arrival enters the system without changing B, RS, or RL.
            if collect:
                counts["fresh_arrivals"] += 1
            admit_caller(
                make_caller(event_time=t, source_type="fresh", attempt_count=0),
                t,
                collect,
            )
        elif event == 1:  # Recertification arrival
            # One individual in B generates a recertification call and leaves B.
            B -= 1
            if collect:
                counts["recertification_arrivals"] += 1
            admit_caller(
                make_caller(
                    event_time=t, source_type="recertification", attempt_count=0
                ),
                t,
                collect,
            )
        elif event == 2:  # Short-redial arrival
            # One short-redial individual returns, leaves RS, and enters the system.
            caller = pop_orbit_caller(short_orbit, "short_orbit_return")
            if collect:
                counts["short_redial_arrivals"] += 1
            admit_caller(caller, t, collect)
        elif event == 3:  # Long-redial arrival
            # One long-redial individual returns, leaves RL, and enters the system.
            caller = pop_orbit_caller(long_orbit, "long_orbit_return")
            if collect:
                counts["long_redial_arrivals"] += 1
            admit_caller(caller, t, collect)
        elif event in (4, 5, 6):  # Waiting-caller abandonment
            # Waiting callers have identical clocks, so choose the abandoner uniformly.
            abandoned_index = int(rng.integers(len(waiting_queue)))
            caller = waiting_queue.pop(abandoned_index)
            if collect:
                abandoned_waits.append(t - caller.queue_entry_time)
            if event == 4:
                # Lost abandonment: the caller does not enter any redial pool.
                caller.attempt_count += 1
                caller.exit_time = t
                caller.current_location = "left_without_enrollment"
                if caller.is_cohort_member(cohort_start, cohort_end):
                    cohort_unfinished_live -= 1
                if collect:
                    counts["abandon_lost"] += 1
            elif event == 5:
                # Short redial: the caller may return later at aggregate rate deltaS * RS.
                add_to_orbit(caller, short_orbit, "short_orbit")
                if collect:
                    counts["abandon_short"] += 1
            else:
                # Long redial: the caller may return later at aggregate rate deltaL * RL.
                add_to_orbit(caller, long_orbit, "long_orbit")
                if collect:
                    counts["abandon_long"] += 1
        elif event in (7, 8):  # Service completion
            # In-service callers have identical clocks, so choose the completer uniformly.
            completed_index = int(rng.integers(len(in_service)))
            caller = in_service.pop(completed_index)
            if event == 7:
                # Successful service: the individual enters B.
                caller.completion_time = t
                caller.current_location = "completed"
                if caller.is_cohort_member(cohort_start, cohort_end):
                    cohort_unfinished_live -= 1
                completed_caller_records.append(
                    {
                        "caller_id": caller.caller_id,
                        "first_arrival_time": float(caller.first_arrival_time),
                        "completion_time": t,
                        "time_to_enrollment": t - float(caller.first_arrival_time),
                        "attempt_count": caller.attempt_count,
                        "cohort_member": caller.is_cohort_member(
                            cohort_start, cohort_end
                        ),
                    }
                )
                if collect:
                    completed_attempt_records.append(caller.attempt_count)
                B += 1
                if collect:
                    counts["service_successes"] += 1
            else:
                # Failed service: the individual enters the long-redial pool RL.
                add_to_orbit(caller, long_orbit, "long_orbit")
                if collect:
                    counts["service_failures"] += 1
            # When a server frees up, admit the next waiting caller under FCFS.
            start_next_waiting(t, collect)
        else:  # Enrolled departure
            # Natural departure from B without generating a call.
            B -= 1

        # Update diagnostics after each event to check nonnegativity and capacity.
        Q = len(waiting_queue) + len(in_service)
        RS = orbit_count(short_orbit)
        RL = orbit_count(long_orbit)
        min_Q = min(min_Q, Q)
        min_B = min(min_B, B)
        min_RS = min(min_RS, RS)
        min_RL = min(min_RL, RL)
        max_in_service = max(max_in_service, len(in_service))
        if validate:
            _validate_simulation_state(
                t=t,
                event=event,
                rates=None,
                total_rate=None,
                B=B,
                RS=RS,
                RL=RL,
                waiting_count=len(waiting_queue),
                service_count=len(in_service),
                capacity=params.c,
                require_positive_total_rate=False,
            )

        if dynamic_horizon and max_events is not None and events_processed >= max_events:
            termination_reason = "max_events"
            break

        if dynamic_horizon and dynamic_stop_time is None and t >= float(cohort_end):
            if cohort_size_collected > 0 and cohort_unfinished_live == 0:
                cohort_clearance_time = t
                dynamic_stop_time = min(t + post_clearance_buffer, simulation_limit)

    # Observation time used for averages and rates, excluding warmup.
    simulation_end_time = t
    if dynamic_horizon:
        if cohort_size_collected == 0 and termination_reason != "max_events":
            termination_reason = "zero_cohort"
        elif termination_reason == "fixed_horizon":
            if cohort_size_collected == 0:
                termination_reason = "zero_cohort"
            elif cohort_unfinished_live > 0:
                termination_reason = "max_dynamic_horizon"
            else:
                termination_reason = "cohort_cleared_buffer_elapsed"
        dynamic_horizon_success = (
            termination_reason == "cohort_cleared_buffer_elapsed"
            and cohort_size_collected > 0
            and cohort_unfinished_live == 0
        )
    observation_time = max(simulation_end_time - params.warmup, 0.0)
    # Total arrivals are the four event types that enter the system.
    total_arrivals = sum(
        counts[name]
        for name in (
            "fresh_arrivals",
            "recertification_arrivals",
            "short_redial_arrivals",
            "long_redial_arrivals",
        )
    )
    # Total abandonments are the three abandonment routes.
    total_abandonments = sum(
        counts[name] for name in ("abandon_lost", "abandon_short", "abandon_long")
    )
    # Overall wait includes both answered and abandoned callers.
    all_waits = answered_waits + abandoned_waits

    def mean_minutes(values: list[float]) -> float:
        """Convert a list of model-day waits to an average in minutes."""

        return (
            (float(np.mean(values)) * MINUTES_PER_MODEL_DAY)
            if len(values) > 0
            else 0.0
        )

    result_values = {
        "total_arrivals": total_arrivals,
        "fresh_arrivals": counts["fresh_arrivals"],
        "recertification_arrivals": counts["recertification_arrivals"],
        "short_redial_arrivals": counts["short_redial_arrivals"],
        "long_redial_arrivals": counts["long_redial_arrivals"],
        "total_abandonments": total_abandonments,
    }
    repeat_attempt_proxies = compute_repeat_attempt_proxies(result_values)
    attempt_summary = summarize_attempt_records(completed_attempt_records)
    final_RS = orbit_count(short_orbit)
    final_RL = orbit_count(long_orbit)

    # Package event counts, time averages, wait metrics, and diagnostics.
    result = SimulationResult(
        total_arrivals=total_arrivals,
        fresh_arrivals=counts["fresh_arrivals"],
        recertification_arrivals=counts["recertification_arrivals"],
        short_redial_arrivals=counts["short_redial_arrivals"],
        long_redial_arrivals=counts["long_redial_arrivals"],
        service_successes=counts["service_successes"],
        service_failures=counts["service_failures"],
        abandon_lost=counts["abandon_lost"],
        abandon_short=counts["abandon_short"],
        abandon_long=counts["abandon_long"],
        total_abandonments=total_abandonments,
        mean_Q=areas["Q"] / observation_time,
        mean_waiting=areas["waiting"] / observation_time,
        mean_B=areas["B"] / observation_time,
        mean_RS=areas["RS"] / observation_time,
        mean_RL=areas["RL"] / observation_time,
        utilization=(
            areas["busy"] / (params.c * observation_time) if params.c > 0 else 0.0
        ),
        average_wait_including_abandonments_minutes=mean_minutes(all_waits),
        average_speed_to_answer_minutes=mean_minutes(answered_waits),
        average_time_to_abandonment_minutes=mean_minutes(abandoned_waits),
        abandonment_fraction=(
            total_abandonments / total_arrivals if total_arrivals > 0 else 0.0
        ),
        procedural_denial_rate_per_model_day=counts["abandon_lost"] / observation_time,
        total_arrival_rate_per_model_day=total_arrivals / observation_time,
        effective_arrival_rate_per_model_day=(total_arrivals - total_abandonments)
        / observation_time,
        returning_call_rate_per_model_day=(
            counts["recertification_arrivals"]
            + counts["short_redial_arrivals"]
            + counts["long_redial_arrivals"]
        )
        / observation_time,
        final_Q=len(waiting_queue) + len(in_service),
        final_waiting=len(waiting_queue),
        final_in_service=len(in_service),
        final_B=B,
        final_RS=final_RS,
        final_RL=final_RL,
        min_Q=min_Q,
        min_B=min_B,
        min_RS=min_RS,
        min_RL=min_RL,
        max_in_service=max_in_service,
        **repeat_attempt_proxies,
        **attempt_summary,
    )

    def end_state_distribution(only_cohort: bool = False) -> pd.DataFrame:
        """Return attempt-count distributions for callers still in tracked states."""

        location_callers = {
            "queue": waiting_queue,
            "service": in_service,
            "short_orbit": short_orbit,
            "long_orbit": long_orbit,
        }
        rows = []
        for location, callers in location_callers.items():
            selected = [
                caller
                for caller in callers
                if not only_cohort
                or caller.is_cohort_member(cohort_start, cohort_end)
            ]
            counts_by_attempt = Counter(caller.attempt_count for caller in selected)
            for attempt_count, count in sorted(counts_by_attempt.items()):
                rows.append(
                    {
                        "location": location,
                        "attempt_count": int(attempt_count),
                        "count": int(count),
                    }
                )
        return pd.DataFrame(rows, columns=["location", "attempt_count", "count"])

    caller_records = pd.DataFrame(
        completed_caller_records,
        columns=[
            "caller_id",
            "first_arrival_time",
            "completion_time",
            "time_to_enrollment",
            "attempt_count",
            "cohort_member",
        ],
    )

    def caller_state_row(caller: Caller) -> dict[str, int | float | str | bool | None]:
        """Return a person-level final state row for cohort analysis."""

        if caller.completion_time is not None:
            terminal_outcome = "completed"
            end_time = caller.completion_time
        elif caller.exit_time is not None:
            terminal_outcome = "left_without_enrollment"
            end_time = caller.exit_time
        else:
            terminal_outcome = "unfinished"
            end_time = simulation_end_time
        return {
            "caller_id": caller.caller_id,
            "first_arrival_time": float(caller.first_arrival_time),
            "service_start_time": caller.service_start_time,
            "completion_time": caller.completion_time,
            "exit_time": caller.exit_time,
            "attempt_count": caller.attempt_count,
            "current_location": caller.current_location,
            "terminal_outcome": terminal_outcome,
            "time_in_system": end_time - float(caller.first_arrival_time),
            "is_cohort_member": caller.is_cohort_member(cohort_start, cohort_end),
        }

    cohort_caller_state_records = pd.DataFrame(
        [
            caller_state_row(caller)
            for caller in all_callers.values()
            if caller.is_cohort_member(cohort_start, cohort_end)
        ],
        columns=[
            "caller_id",
            "first_arrival_time",
            "service_start_time",
            "completion_time",
            "exit_time",
            "attempt_count",
            "current_location",
            "terminal_outcome",
            "time_in_system",
            "is_cohort_member",
        ],
    )
    unfinished_rows = []
    for caller in all_callers.values():
        if (
            caller.completion_time is None
            and caller.is_cohort_member(cohort_start, cohort_end)
        ):
            end_time = (
                caller.exit_time if caller.exit_time is not None else simulation_end_time
            )
            unfinished_rows.append(
                {
                    "caller_id": caller.caller_id,
                    "first_arrival_time": float(caller.first_arrival_time),
                    "current_attempt_count": caller.attempt_count,
                    "current_location": caller.current_location,
                    "time_in_system": end_time - float(caller.first_arrival_time),
                }
            )
    unfinished_cohort_callers = pd.DataFrame(
        unfinished_rows,
        columns=[
            "caller_id",
            "first_arrival_time",
            "current_attempt_count",
            "current_location",
            "time_in_system",
        ],
    )

    cohort_size = int(len(cohort_caller_state_records))
    cohort_completed = int(
        (cohort_caller_state_records["terminal_outcome"] == "completed").sum()
    )
    cohort_left_without_enrollment = int(
        (
            cohort_caller_state_records["terminal_outcome"]
            == "left_without_enrollment"
        ).sum()
    )
    cohort_unfinished = int(
        (cohort_caller_state_records["terminal_outcome"] == "unfinished").sum()
    )
    dynamic_horizon_diagnostics = pd.DataFrame(
        [
            {
                "cohort_start": cohort_start,
                "cohort_end": cohort_end,
                "cohort_size": cohort_size,
                "cohort_completed": cohort_completed,
                "cohort_left_without_enrollment": cohort_left_without_enrollment,
                "cohort_unfinished": cohort_unfinished,
                "cohort_clearance_time": cohort_clearance_time,
                "post_clearance_buffer": post_clearance_buffer
                if dynamic_horizon
                else float("nan"),
                "simulation_end_time": simulation_end_time,
                "dynamic_horizon_success": dynamic_horizon_success,
                "events_processed": events_processed,
                "termination_reason": termination_reason,
            }
        ]
    )

    extras_requested = (
        return_caller_records
        or return_end_state_distribution
        or return_cohort_summary
        or dynamic_horizon
    )
    # extra_outputs holds the new analysis tables requested by caller-level flags.
    # It is appended as the final tuple item so older return modes keep their order.
    extra_outputs: dict[str, pd.DataFrame] = {}
    if return_caller_records:
        # caller_records: one row per successful enrollment.
        # unfinished_cohort_callers: cohort callers without successful enrollment by T.
        extra_outputs["caller_records"] = caller_records
        extra_outputs["cohort_caller_state_records"] = cohort_caller_state_records
        extra_outputs["unfinished_cohort_callers"] = unfinished_cohort_callers
    if return_end_state_distribution:
        # end_state_attempt_distribution summarizes active callers still in
        # queue/service/orbits at T; the cohort version filters that table to
        # callers whose first arrival time lies in [cohort_start, cohort_end).
        extra_outputs["end_state_attempt_distribution"] = end_state_distribution()
        extra_outputs["cohort_end_state_attempt_distribution"] = (
            end_state_distribution(only_cohort=True)
        )
    if return_cohort_summary:
        # cohort_summary is a one-row table with cohort size, completion rate,
        # and attempt/time-to-enrollment summary statistics.
        extra_outputs["cohort_summary"] = cohort_summary_table(
            caller_records,
            unfinished_cohort_callers,
            cohort_start=cohort_start,
            cohort_end=cohort_end,
            horizon=simulation_end_time,
        )
    if dynamic_horizon:
        extra_outputs["dynamic_horizon_diagnostics"] = dynamic_horizon_diagnostics

    # Preserve the historical return contract:
    #   simulate_one(...) -> result
    #   return_attempt_records=True -> (result, completed_attempt_records)
    #   record_path=True -> (result, path)
    #   both old flags -> (result, completed_attempt_records, path)
    # New caller/cohort outputs are appended after those legacy outputs.
    outputs: list[object] = [result]
    if return_attempt_records:
        # completed_attempt_records is the legacy list of attempt counts for
        # post-warmup successful enrollments.
        outputs.append(completed_attempt_records)
    if record_path:
        # path is the aggregate sample path of Q, B, RS, and RL over time.
        path = pd.DataFrame(path_rows, columns=["t", "Q", "B", "RS", "RL"])
        outputs.append(path)
    if extras_requested:
        # Include these base caller tables whenever any new extra is requested,
        # so downstream analysis can audit the summary tables if needed.
        extra_outputs.setdefault("caller_records", caller_records)
        extra_outputs.setdefault("cohort_caller_state_records", cohort_caller_state_records)
        extra_outputs.setdefault("unfinished_cohort_callers", unfinished_cohort_callers)
        outputs.append(extra_outputs)
    if len(outputs) == 1:
        return result
    return tuple(outputs)


def run_replications(
    params: SimulationParams, n_replications: int, validate: bool = False
) -> pd.DataFrame:
    """Run independent replications and return one summary row per run.

    n_replications is the number of independent repeated experiments. The
    function derives n_replications child seeds from params.seed so that runs
    are independent while the full replication table remains reproducible for
    the same original seed.
    """

    # The replication count must be positive; bool is excluded despite being an int.
    if not isinstance(n_replications, (int, np.integer)) or isinstance(
        n_replications, bool
    ):
        raise ValueError("n_replications must be an integer")
    if n_replications <= 0:
        raise ValueError("n_replications must be positive")

    # SeedSequence.spawn creates statistically independent child random sequences.
    seed_sequence = np.random.SeedSequence(params.seed)
    child_sequences = seed_sequence.spawn(n_replications)
    rows = []
    for replication, child_sequence in enumerate(child_sequences):
        # Convert the child sequence into an integer seed accepted by simulate_one.
        replication_seed = int(child_sequence.generate_state(1, dtype=np.uint64)[0])
        result = simulate_one(replace(params, seed=replication_seed), validate=validate)
        # Each row keeps the replication id, actual seed, and all result fields.
        row = {"replication": replication, "seed": replication_seed}
        row.update(result.to_dict())
        rows.append(row)

    return pd.DataFrame(rows)
